"""
Agent 4 - Test Agent for Processing Pipeline

This is a scaffolding agent for testing the agent processing pipeline.
Functionality will be added between status states.
"""
import asyncio
import json
import time
from typing import Optional
from app.services.websocket_manager import WebSocketManager
from app.services.storage import StorageService


async def agent_4_process(
    websocket_manager: WebSocketManager,
    user_id: str,
    session_id: str,
    supersessionid: str,
    storage_service: Optional[StorageService] = None
):
    """
    Agent4: Second agent in the processing pipeline.
    
    This is scaffolding - functionality will be added between status states.
    
    Args:
        websocket_manager: WebSocket manager for status updates
        user_id: User identifier
        session_id: Session identifier
        supersessionid: Super session identifier (generated by Agent2)
        storage_service: Storage service for S3 operations
    """
    # Initialize storage service if not provided
    if storage_service is None:
        storage_service = StorageService()
    
    # Helper function to create JSON status file in S3
    async def create_status_json(agent_number: str, status: str, status_data: dict):
        """Create a JSON file in S3 with status data."""
        if not storage_service.s3_client:
            return  # Skip if storage not configured
        
        timestamp = int(time.time() * 1000)  # Milliseconds timestamp
        filename = f"agent_{agent_number}_{status}_{timestamp}.json"
        s3_key = f"scaffold_test/{user_id}/{supersessionid}/{filename}"
        
        try:
            json_content = json.dumps(status_data, indent=2).encode('utf-8')
            storage_service.s3_client.put_object(
                Bucket=storage_service.bucket_name,
                Key=s3_key,
                Body=json_content,
                ContentType='application/json'
            )
        except Exception as e:
            # Log but don't fail the pipeline if JSON creation fails
            print(f"Failed to create status JSON file: {e}")
    
    try:
        # Report starting status
        status_data = {
            "agentnumber": "Agent4",
            "userID": user_id,
            "sessionID": session_id,
            "supersessionID": supersessionid,
            "status": "starting",
            "timestamp": int(time.time() * 1000)
        }
        await websocket_manager.send_progress(session_id, status_data)
        await create_status_json("4", "starting", status_data)
        
        # Wait 2 seconds
        await asyncio.sleep(2)
        
        # TODO: Add initialization/preparation logic here
        
        # Report processing status
        status_data = {
            "agentnumber": "Agent4",
            "userID": user_id,
            "sessionID": session_id,
            "supersessionID": supersessionid,
            "status": "processing",
            "timestamp": int(time.time() * 1000)
        }
        await websocket_manager.send_progress(session_id, status_data)
        await create_status_json("4", "processing", status_data)
        
        # Wait 2 seconds
        await asyncio.sleep(2)
        
        # TODO: Add main agent work here (e.g., video composition, processing)
        
        # Report finished status
        status_data = {
            "agentnumber": "Agent4",
            "userID": user_id,
            "sessionID": session_id,
            "supersessionID": supersessionid,
            "status": "finished",
            "timestamp": int(time.time() * 1000)
        }
        await websocket_manager.send_progress(session_id, status_data)
        await create_status_json("4", "finished", status_data)
        
        # TODO: Add cleanup/finalization logic here
        
        # Trigger Agent5 with userID, sessionID, and supersessionid
        from app.agents.agent_5 import agent_5_process
        await agent_5_process(websocket_manager, user_id, session_id, supersessionid, storage_service)
        
    except Exception as e:
        # Report error status and stop pipeline
        error_data = {
            "agentnumber": "Agent4",
            "userID": user_id,
            "sessionID": session_id,
            "supersessionID": supersessionid,
            "status": "error",
            "error": str(e),
            "reason": f"Agent4 failed: {type(e).__name__}",
            "timestamp": int(time.time() * 1000)
        }
        await websocket_manager.send_progress(session_id, error_data)
        await create_status_json("4", "error", error_data)
        raise  # Stop pipeline on error

